services:
    auth.provider.shibboleth:
        class: ckws\authshibboleth\auth\provider\shibboleth
        arguments:
            - @dbal.conn
            - @config
            - @request
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: auth.provider }